name: QuAcK CI


on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'
  schedule:
  - cron: "42 19 * * 6"


jobs:

  build:
    runs-on: ubuntu-24.04
    name: Compilation and Tests

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gfortran gcc liblapack-dev libblas-dev wget python3 make m4 pkg-config
 
    - name: Configuration
      run: |
        ./configure -i ninja || :

    - name: Compilation
      run: |
        set -e
        source quack.rc
        cd src
        make

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyscf

    - name: Run tests
      run: |
        set -e
        set -o pipefail
        source quack.rc
        cd test
        python generate_test_methods_and_options.py
        cp methods.test ../tests/inp/methods.RHF
        cp options.test ../tests/inp/options.RHF
        cd ../tests
        python create_database.py
        python lunch_bench.py -s light -t 1e-1
